import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="flex justify-between items-center p-12 gap-4 h-16">
            <div className="flex items-center gap-2">
              {/* Logo - 4 small squares in a 2x2 grid */}
              <div className="relative w-8 h-8 grid grid-cols-2 grid-rows-2 gap-0.5">
                <div className="bg-indigo-600 rounded-sm"></div>
                <div className="bg-pink-800 rounded-sm"></div>
                <div className="bg-pink-500 rounded-sm"></div>
                <div className="bg-indigo-600 rounded-sm"></div>
              </div>

              {/* Text with gradient */}
              <Link
                href="/"
                className="text-2xl font-bold leading-7 bg-gradient-to-r from-indigo-900  text-transparent bg-clip-text"
              >
                Rudoria
              </Link>
            </div>
            <SignedOut>
              <SignInButton>
                <button className="inline-flex h-10 items-center text-white justify-center rounded-md border bg-indigo-600  px-8 text-sm font-medium  transition-colors hover:bg-indigo-500 cursor-pointer focus-visible:outline-none focus-visible:ring-2 disabled:opacity-50">
                  Sign in
                </button>
              </SignInButton>
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
